//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLyVeSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA
    {
        public int MAKQ { get; set; }
        public Nullable<int> MAVS { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> MAGIAI { get; set; }
        public string SOTRUNG { get; set; }
    
        public virtual GIAI GIAI { get; set; }
        public virtual VESO VESO { get; set; }
    }
}
