//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLyVeSo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLUONGDANGKY
    {
        public int MASLDK { get; set; }
        public Nullable<int> MADL { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> SLDANGKY { get; set; }
    
        public virtual DAILY DAILY { get; set; }
    }
}
