--- create the database ---
USE [master]
GO
DROP DATABASE [DAILYVESO]
GO
CREATE DATABASE [DAILYVESO]
ON
(
	NAME = 'QLCB_Data',
	FILENAME = 'D:\SGU\00_NOW\_PHAN_MEM_QUAN_LY\BaiTap_Rieng\DLVS_Data.mdf',
	SIZE = 10MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 5MB
)
LOG ON
(
	NAME = 'QLCB_Log',
	FILENAME='D:\SGU\00_NOW\_PHAN_MEM_QUAN_LY\BaiTap_Rieng\DLVS_Log.ldf',
	SIZE = 5MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 2MB
)
GO

--- create the tables ---

USE [DAILYVESO]
GO
CREATE TABLE [VESO]
(
	[MAVS] [INT] NOT NULL,
	[TINH] [NVARCHAR](100) NULL,
	CONSTRAINT [PK_VESO] PRIMARY KEY ([MAVS])
)
GO
CREATE TABLE [DAILY]
(
	[MADL] [INT] NOT NULL,
	[TEN] [NVARCHAR](100) NULL,
	CONSTRAINT [PK_DAILY] PRIMARY KEY ([MADL])
)
GO
CREATE TABLE [SOLUONGDANGKY](
	[MASLDK] [INT] NOT NULL,
	[MADL] [INT] NULL,
	[NGAY] [DATE] NULL,
	[SLDANGKY] [INT] NULL,
	CONSTRAINT [PK_SOLUONGDANGKY] PRIMARY KEY ([MASLDK])
)
GO
CREATE TABLE [PHANPHOI]
(
	[MAPP] [INT] NOT NULL,
	[MAVS] [INT] NULL,
	[MADL] [INT] NULL,
	[NGAY] [DATE] NULL,
	[SLGIAO] [INT] NULL,
	[SLBAN] [INT] NULL,
	CONSTRAINT [PK_PHANPHOI] PRIMARY KEY ([MAPP])
)
GO
CREATE TABLE [GIAI](
	[MAGIAI] [INT] NOT NULL,
	[TEN] [NVARCHAR](50) NULL,
	CONSTRAINT [PK_GIAI] PRIMARY KEY ([MAGIAI])
)
GO
CREATE TABLE [KETQUA](
	[MAKQ] [INT] NOT NULL,
	[MAVS] [INT] NULL,
	[NGAY] [DATE] NULL,
	[MAGIAI] [INT] NULL,
	[SOTRUNG] [VARCHAR](6) NULL,
	CONSTRAINT [PK_KETQUA] PRIMARY KEY ([MAKQ])
)
GO
CREATE TABLE [PHIEUTHU](
	[MAPT] [INT] NOT NULL,
	[MADL] [INT] NULL,
	[NGAY] [DATE] NULL,
	[TIEN] [MONEY] NULL,
	CONSTRAINT [PK_PHIEUTHU] PRIMARY KEY ([MAPT])
)
GO
CREATE TABLE [PHIEUCHI](
	[MAPC] [INT] NOT NULL,
	[NGAY] [DATE] NULL,
	[TIEN] [MONEY] NULL,
	CONSTRAINT [PK_PHIEUCHI] PRIMARY KEY ([MAPC])
)
GO

--- Add the foreign key ---

ALTER TABLE [SOLUONGDANGKY]
ADD CONSTRAINT [FK_SOLUONGDANGKY_MADL]
	FOREIGN KEY ([MADL])
	REFERENCES [DAILY]([MADL])
GO
ALTER TABLE [PHANPHOI]
ADD CONSTRAINT [FK_PHANPHOI_MAVS]
	FOREIGN KEY ([MAVS])
	REFERENCES [VESO]([MAVS])
GO
ALTER TABLE [PHANPHOI]
ADD CONSTRAINT [FK_PHANPHOI_MADL]
	FOREIGN KEY ([MADL])
	REFERENCES [DAILY]([MADL])
GO
ALTER TABLE [KETQUA]
ADD CONSTRAINT [FK_KETQUA_MAVS]
	FOREIGN KEY ([MAVS])
	REFERENCES [VESO]([MAVS])
GO
ALTER TABLE [KETQUA]
ADD CONSTRAINT [FK_KETQUA_MAGIAI]
	FOREIGN KEY ([MAGIAI])
	REFERENCES [GIAI]([MAGIAI])
GO
ALTER TABLE [PHIEUTHU]
ADD CONSTRAINT [FK_PHIEUTHU_MADL]
	FOREIGN KEY ([MADL])
	REFERENCES [DAILY]([MADL])
GO

--- Insert the test data ---

INSERT INTO VESO VALUES('1',N'Tỉnh 1')
INSERT INTO VESO VALUES('2',N'Tỉnh 2')
INSERT INTO VESO VALUES('3',N'Tỉnh 3')

INSERT INTO DAILY VALUES('1',N'Đại lí 1')
INSERT INTO DAILY VALUES('2',N'Đại lí 2')
INSERT INTO DAILY VALUES('3',N'Đại lí 3')

INSERT INTO GIAI VALUES('0',N'Giải đặc biệt')
INSERT INTO GIAI VALUES('1',N'Giải nhất')
INSERT INTO GIAI VALUES('2',N'Giải nhì')
INSERT INTO GIAI VALUES('3',N'Giải ba')
INSERT INTO GIAI VALUES('4',N'Giải tư')
INSERT INTO GIAI VALUES('5',N'Giải năm')
INSERT INTO GIAI VALUES('6',N'Giải sáu')
INSERT INTO GIAI VALUES('7',N'Giải bảy')
INSERT INTO GIAI VALUES('8',N'Giải tám')


--- show the tables ---

SELECT * FROM VESO;
GO
SELECT * FROM DAILY;
GO
SELECT * FROM SOLUONGDANGKY;
GO
SELECT * FROM PHANPHOI;
GO
SELECT * FROM GIAI;
GO
SELECT * FROM KETQUA;
GO
SELECT * FROM PHIEUTHU;
GO
SELECT * FROM PHIEUCHI;
GO

--- the end ---